apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect-app
  labels:
    app: kafka-connect-app
  namespace: bigdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect-app
  template:
    metadata:
      labels:
        app: kafka-connect-app
    spec:
      volumes:
        - name: connect-storage
          persistentVolumeClaim:
            claimName: kafka-connect-pv-claim
      containers:
        - name: kafka-connect-container 
          image: confluentinc/cp-kafka-connect:latest
          ports:
            - containerPort: 8083
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: "kafka-svc:9092"
            - name: CONNECT_REST_PORT
              value: "28085"
            - name: CONNECT_GROUP_ID
              value: "1"
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: "kafka-connect-configs"
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: "kafka-connect-offsets"
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: "kafka-connect-status"
            - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
              value: "2"
            - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
              value: "2"
            - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
              value: "2"
            - name: CONNECT_REPLICATION_FACTOR
              value: "2"
            - name: CONNECT_OFFSET_FLUSH_INTERVAL_MS
              value: "2000"
            - name: CONNECT_KEY_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_INTERNAL_KEY_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_INTERNAL_VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              value: "kafka-connect-app"
            - name: CONNECT_REST_ADVERTISED_PORT
              value: "8083"
          volumeMounts:
            - name: connect-storage
              mountPath: /mnt/connect